import type { Metadata } from "next";
import { fontVariables } from "@/fonts";
import "@/styles/globals.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Главная страница",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={fontVariables}>
      <body>
        <Toaster position="top-right" richColors closeButton />
        <Header />

        <div className="app-layout">
          <Sidebar />
          <main className="main-content">{children}</main>
        </div>
      </body>
    </html>
  );
}
