import type { Metadata } from "next";
import { fontVariables } from "@/fonts";
import "@/styles/globals.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "sonner";
import Footer from "@/components/Footer/Footer";
import MobileNav from "@/components/ui/MobileNav/MobileNav";

export const metadata: Metadata = {
  title: "Главная страница",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={fontVariables}>
      <body className="root-body">
        <Toaster
          position="top-right"
          offset="16px"
          gap={8}
          expand={false}
          richColors
          closeButton
        />
        <Header />

        <div className="app-layout">
          <Sidebar />
          <main className="main-content">{children}</main>
        </div>
        <MobileNav />
        <Footer />
      </body>
    </html>
  );
}
