import type { Metadata } from "next";
import { fontVariables } from "@/fonts";
import "@/styles/globals.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "sonner";
import Footer from "@/components/Footer/Footer";
import MobileNav from "@/components/ui/MobileNav/MobileNav";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getProfile } from "@/services/profileService";

export const metadata: Metadata = {
  title: "Главная страница",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const profile = user ? await getProfile(user.id) : null;

  return (
    <html lang="ru" className={fontVariables} suppressHydrationWarning>
      <body className="root-body">
        <AuthProvider initialUser={user} initialProfile={profile}>
          <ThemeProvider>
            <Toaster
              position="top-right"
              offset="16px"
              gap={8}
              expand={false}
              richColors
              closeButton
            />
            <Header />

            <div className="app-layout">
              <Sidebar />
              <main className="main-content">{children}</main>
            </div>
            <MobileNav />
            <Footer />
          </ThemeProvider>
        </AuthProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
